api:
  dashboard: true

experimental:
  http3: true

log:
  level: INFO
  filePath: /dev/stdout

accesslog: {}

entrypoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https
          permanent: true
          priority: 2147483646
    http3:
      advertisedport: 443

  https:
    address: ":443"
    http:
      middlewares:
        - security-headers@file
        - rate-limiting@file
      tls:
        domains:
          - main: example.com
            sans:
              - "*.example.com"
    http3:
      advertisedport: 443

providers:
  docker:
    network: traefik
    exposedbydefault: false
    endpoint: unix:///var/run/docker.sock
  file:
    directory: /etc/traefik/configs
    watch: true
